language: python
sudo: false
python:
  - "2.7"
env:
  - DJANGO_VERSION=">=1.8,<1.8.99"
install:
  # Force specific version of Django
  - pip install -q Django$DJANGO_VERSION
  - pip install -r requirements-dev.txt
  - pip install -e .
  - pip list
script:
  - make check-isort
  - make check-flake8
  - make check-migrations
  - make check-i18n
  - make check-test
