language: python
sudo: false
python:
  - "2.7"
env:
  - DJANGO_VERSION=1.7.11
install:
  - pip install -r requirements.txt
  # Force specific version of Django
  - pip install -q Django==$DJANGO_VERSION
  - pip install isort
  - pip install flake8
  - pip install -e .
  - pip list
script:
  - make check-isort
  - make check-flake8
  - make check-migrations
  - make check-test
